version: 2.1

defaults: &defaults
  docker:
  - image: golang:stretch
  working_directory: /workspace
  environment:
    GOPATH: /
    GOCACHE: /.cache/go-build
    GO111MODULE: "on"

jobs:
  setup-build:
    <<: *defaults
    steps:
    - run: go env
    - checkout
    - restore_cache:
        keys:
        - go-module-cache-v1-{{ checksum "/workspace/src/go.sum" }}
        - go-module-cache-v1-
    - run: go mod download
    - save_cache:
        key: go-module-cache-v1-{{ checksum "/workspace/src/go.sum" }}
        paths:
        - /pkg/mod/cache
    - save_cache:
        key: workspace-v1-{{ .Environment.CIRCLE_SHA1 }}
        paths:
        - /workspace/src